---

- hosts: all
  become: true
  tasks:

    - name: Install apache2, php and update repository index on Ubuntu hosts
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest   
        update_cache: yes
      when: inventory_hostname in groups['Ubuntu']


    - name: Install httpd, php and update repository index on Oracle Linux hosts
      dnf:
        name:
          - httpd
          - php
        state: latest   
        update_cache: yes
      when: inventory_hostname in groups['OracleLinux']
