---

- hosts: Ubuntu
  become: true
  tasks:

    - name: Update repository index on Ubuntu hosts
      apt:
        update_cache: yes

    - name: Install apache2 package on Ubuntu hosts
      apt:
        name: apache2

    - name: Add php support for Apache on Ubuntu hosts
      apt:
        name: libapache2-mod-php
