---

- hosts: Ubuntu
  become: true
  tasks:

    - name: Remove apache2, php packages and update cache on Ubuntu hosts
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: absent
        update_cache: yes

- hosts: OracleLinux
  become: true
  tasks:

    - name: Remove httpd, php packages and update cache on Oracle Linux
      ansible.builtin.dnf:
        name:
          - httpd
          - php
        state: absent
        update_cache: yes
