---

- hosts: all
  become: true
  tasks:

    - name: Remove apache and php packages from  Ubuntu servers
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: absent
      when: ansible_distribution == "Ubuntu"

    - name: Remove apache and php packages from Oracle Linux servers
      ansible.builtin.dnf:
        name:
          - httpd
          - php
        state: absent
        update_cache: yes
      when: ansible_distribution == "OracleLinux"
